### ISSUE TITLE
\install\prefix\ path does not fully work

### ISSUE THREAD

**Issue by crtolle** [cilkplus/clang#1]
Just as a check I compiled the code and installed it to \install\prefix which should work.  This was meant simply as a test!  However when one tries to compile the code -- there appears to be a hardcoded reference to \usr\local\include\cilk which doesn't work since the prefix has moved this location.

/install/prefix/bin/clang -fcilkplus test.c -o test -lcilkrts
test.c:1:10: fatal error: 'cilk/cilk.h' file not found
# include <cilk/cilk.h>

```
     ^
```

1 error generated.
ld: file not found: /var/folders/kn/vgt9y5xs2fd_y1vc_xw_71580000gn/T/test-4ZnKQT.o
clang-3: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Drew92** [comment]
@benlangmuir I tried to putting all the export paths inside the cilkvar.sh script and ran the "source cilkvar.sh" command. But it didn't work, is it because I had the cilkvar.sh file in the same directory as test.c ? or is there something else I need to do? please help

**Comment by juraev** [comment]
HI, @benlangmuir. I am having a problem:

$/usr/local/opt/tapir/bin/clang -fcilkplus fib.cpp
In file included from fib.cpp:3:
In file included from /usr/local/Cellar/tapir/HEAD-6817533/include/c++/v1/iostream:38:
In file included from /usr/local/Cellar/tapir/HEAD-6817533/include/c++/v1/ios:215:
In file included from /usr/local/Cellar/tapir/HEAD-6817533/include/c++/v1/iosfwd:90:
/usr/local/Cellar/tapir/HEAD-6817533/include/c++/v1/wchar.h:119:15: fatal error: 'wchar.h' file
      not found
#include_next <wchar.h>
