### ISSUE TITLE
Cannot compile the example after building the compiler

### ISSUE THREAD

**Issue by hskim** [cilkplus/clang#18]
Hi,

I tried the compiler recently (02/04/16) and I could not compile the example. The specific error was about it cannot find cilk.h. After make install, I setup all the environment variables as instructed on the web page, replacing /install/prefix with $CILKPATH of my own, FYI. I managed to copy one from $SRC/projects/compiler-rt/lib/cilk/include/cilk into $CILKPATH/include, again where $CILKPATH is my own install directory. With that, it finds the header but this time it fails to link, as it cannot find the library. As I search the build directory, the library is not even there. I think there is something broken in the build system regarding installing header files and making libraries.

Could you please take a look? I followed exactly the same instruction on the page.

Sincerely,
Hee-Seok

**Comment by avt77** [comment]
Hi,

Of course you should tune your environment to be able to build examples.
You did it properly for INCLUDE but you should do the same for LD_LIBRARY_PATH
if you use Linux.

There is a small script in the root called "_build.sh": look in it. If you
don't have runtime you should build it and the script will help you to do
it:

CLANG_HOME=`pwd`/new-git-cilk-Feb-2-3
BUILD_HOME=$CLANG_HOME/build

git clone -b cilkplus https://github.com/cilkplus/llvm $CLANG_HOME
git clone -b cilkplus https://github.com/cilkplus/clang
$CLANG_HOME/tools/clang
git clone -b cilkplus https://github.com/cilkplus/compiler-rt
$CLANG_HOME/projects/compiler-rt

rm -rf $BUILD_HOME
mkdir $BUILD_HOME
cd $BUILD_HOME

cmake -G "Unix Makefiles" -DINTEL_SPECIFIC_CILKPLUS=1
-DLLVM_ENABLE_ASSERTIONS=ON
-DCMAKE_BUILD_TYPE=Debug -DCMAKE_VERBOSE_MAKEFILE=1 .. 2>&1 | tee config.log
make -j 8 2>&1 | tee build.log
export PATH=$BUILD_HOME/bin:$PATH

mkdir cilkrt
cd cilkrt
cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
-DCMAKE_INSTALL_PREFIX=$BUILD_HOME
$CLANG_HOME/projects/compiler-rt/lib/cilk 2>&1 | tee config.log
make 2>&1 | tee build.log
make install 2>&1 | tee install.log

If you build and install the runtime then libraries will be placed in
"build/lib" and includes will be copied to "build/include".

Hope it will help you,

# Andrew

Software Engineer
Intel Compiler Team

2016-02-05 11:12 GMT+03:00 hskim notifications@github.com:

**Comment by hskim** [comment]
Thank you for the troubleshooting. I followed the instructions, without a success but figured out that my CMake is stale. After updating it to 3.4, it works like a charm: installing the compiler, building the fibonacci example and running it.

Thumbs up and thank you so much!
